	  <footer>
        <div class="dropup">
            <button class="button">Email the Creators!</button>
            <div class="mail_links">
                <a href="mailto:103831863@swin.edu.au">Shreeya Shrestha</a>
                <a href="mailto:102363543@swin.edu.au">Joshua White</a>
                <a href="mailto:103818882@swin.edu.au">Joy</a>
                <a href="mailto:103835483@swin.edu.au">Ali</a>
                <a href="mailto:103531273@swin.edu.au">Ankit</a>
            </div>
        </div>
        <div class="uni" id="uni-id">
            <a href="https://www.swinburne.edu.au/">Swinburne Homepage</a>
        </div>
        <div class="home">
            <a href="index.php">Back to Homepage</a>
        </div>
    </footer>