 <header id="head1">
   <nav class="header-index" id="common_header">
        <a class="a-index" href="index.php">Homepage</a>
        <a class="a-index" href="topic.php">About IoT</a>
        <a class="a-index" href="quiz.php">Quiz</a>
        <a class="a-index" href="enhancements.html">Enhancements</a>
        <a class="a-index" href="login.php">Manage</a>
        <a class="a-index" href="enhancement2.html">PHP Enhancements</a>
    </nav>
</header>